name: Build and Deploy
on:
  push:
    branches: [ main ]  # Change to your primary branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'  # Match your local version exactly
          
      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install
        
      - name: Build project
        run: |
          # Set CI=false to prevent ESLint warnings from failing the build
          CI=false npm run build
        
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server:ftp.michaelabouzeid.com
          username:michaelaz774@michaelabouzeid.com
          password:portfoliosite13
          local-dir: ./build/
          server-dir: /public_html/
          port: 21