name: Build and Deploy
on:
  push:
    branches: [ main ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'  
          
      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install
        
      - name: Build project
        run: |
          # Set CI=false to prevent ESLint warnings from failing the build
          CI=false npm run build
        
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ../../public_html/
          port: 21
          protocol: ftp
          dangerous-clean-slate: true